### ISSUE TITLE
[Feature]: add a page for djago and add a icon for it and change tailwind to css frameworks in webd page

### ISSUE THREAD

**Issue by mnnkhndlwl** [NSCC-BPIT/NSCC-BPIT-Website#145] opened 2023-10-02 13:28 UTC
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/75252077/b535fa7f-f1e6-46be-ab05-4a65d499f234)

**Comment by Rehan52004** [comment] 2023-10-02 13:37
please assign to me this feature.

**Comment by mnnkhndlwl** [comment] 2023-10-02 13:54
@Rehan52004 we have already assigned you an issue

**Comment by Gauravtb2253** [comment] 2023-10-02 13:57
I can work on it. Please assign me this task.

**Comment by Dev-sAHSRAH** [comment] 2023-10-02 14:53
can you please assign this to me?

There's already a django logo showing up presently and hece other required change is:
![Screenshot 2023-10-02 202122](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/97530701/7e670751-ed48-4253-a397-5507438a613d)

If I have understood it rightly, I would like to contribute to it.

**Comment by mnnkhndlwl** [comment] 2023-10-02 15:38
in backend there is no image for django

**Comment by Dev-sAHSRAH** [comment] 2023-10-02 17:03
I have completed the task!

**Comment by Dev-sAHSRAH** [comment] 2023-10-02 18:05
I mean the PR has already been merged, and you can look at the change in the website. But the issue is not closed.

**Closed** 2023-10-02 18:09 UTC
Labels: good first issue, hacktoberfest, javascript, css, tailwind
